### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by conr2d** [conr2d/eosbancor#1]
## ToDo

- [x] Charge conversion fee (e3d7411ff4ecc3a4c0859062a7741b599617844e)
- [x] Convert exact amount of token to be retrieved (506d4d51262a59e34d14559662ba050e2e7b2496)
- [ ] ~~Add RAM saving version~~
